defaults:
  esphome_device_id: ""
  # name: ""
  # device_id: ""
  # serial_number: ""

external_components:
  # We use a fixed version to ensure compatibility with the current version of the Zendure bridge.
  # When changing the component, make sure to update the version here.
  - source: github://danez/esphome-zendure-bridge@1.1.0
    components: [zendure]

esphome:
  min_version: "2026.1.0"
  on_boot:
    - then:
        - lambda: |-
            id(${device_id}_batteries).insert(
              std::make_pair("${serial_number}", [](JsonObject pack) -> void {
                // Define a map of handlers for each key
                static const sensor_handler_map_t handlers = {
                  {"sn", [](int value) { /* ignore */ }},
                  {"power", [](int value) { publish_state_if_changed(id(${device_id}_battery_${serial_number}_power), value); }},
                  {"minVol", [](int value) { publish_state_if_changed(id(${device_id}_battery_${serial_number}_minVol), value / VOLTAGE_SCALE); }},
                  {"maxVol", [](int value) { publish_state_if_changed(id(${device_id}_battery_${serial_number}_maxVol), value / VOLTAGE_SCALE); }},
                  {"totalVol", [](int value) { publish_state_if_changed(id(${device_id}_battery_${serial_number}_totalVol), value / VOLTAGE_SCALE); }},
                  {"soh", [](int value) { publish_state_if_changed(id(${device_id}_battery_${serial_number}_soh), value / PERCENT_SCALE); }},
                  {"socLevel", [](int value) { publish_state_if_changed(id(${device_id}_battery_${serial_number}_socLevel), value); }},
                  {"softVersion", [](int value) { publish_state_if_changed(id(${device_id}_battery_${serial_number}_softVersion), decode_version(value).c_str()); }},
                  {"maxTemp", [](int value) { publish_state_if_changed(id(${device_id}_battery_${serial_number}_maxTemp), (value / TEMPERATURE_SCALE) - TEMPERATURE_OFFSET); }},
                  {"state", [](int value) {
                    const char* state = (value == 0) ? "Idle" : (value == 1) ? "Charging" : "Discharging";
                    publish_state_if_changed(id(${device_id}_battery_${serial_number}_state), state);
                  }}
                };

                handle_sensor_object(pack, handlers, "${device_id}");
              })
            );

json:
zendure:

sensor:
  - platform: template
    id: "${device_id}_battery_${serial_number}_power"
    name: "${name} Power"
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
    accuracy_decimals: 0
    device_id: "${esphome_device_id}"
  - platform: template
    id: "${device_id}_battery_${serial_number}_minVol"
    name: "${name} Min Vol"
    device_class: voltage
    state_class: measurement
    unit_of_measurement: "V"
    accuracy_decimals: 2
    device_id: "${esphome_device_id}"
  - platform: template
    id: "${device_id}_battery_${serial_number}_maxVol"
    name: "${name} Max Vol"
    device_class: voltage
    state_class: measurement
    unit_of_measurement: "V"
    accuracy_decimals: 2
    device_id: "${esphome_device_id}"
  - platform: template
    id: "${device_id}_battery_${serial_number}_totalVol"
    name: "${name} Total Vol"
    device_class: voltage
    state_class: measurement
    unit_of_measurement: "V"
    accuracy_decimals: 2
    device_id: "${esphome_device_id}"
  - platform: template
    id: "${device_id}_battery_${serial_number}_soh"
    name: "${name} SoH"
    state_class: measurement
    icon: "mdi:battery-heart-variant"
    unit_of_measurement: "%"
    accuracy_decimals: 1
    entity_category: diagnostic
    disabled_by_default: true
    device_id: "${esphome_device_id}"
  - platform: template
    id: "${device_id}_battery_${serial_number}_socLevel"
    name: "${name} SoC Level"
    device_class: battery
    state_class: measurement
    unit_of_measurement: "%"
    accuracy_decimals: 0
    device_id: "${esphome_device_id}"
  - platform: template
    id: "${device_id}_battery_${serial_number}_maxTemp"
    name: "${name} Max Temp"
    device_class: temperature
    state_class: measurement
    unit_of_measurement: "°C"
    accuracy_decimals: 2
    entity_category: diagnostic
    disabled_by_default: true
    device_id: "${esphome_device_id}"

text_sensor:
  - platform: template
    id: "${device_id}_battery_${serial_number}_softVersion"
    name: "${name} Soft Version"
    entity_category: diagnostic
    disabled_by_default: true
    device_id: "${esphome_device_id}"
  - platform: template
    id: "${device_id}_battery_${serial_number}_state"
    name: "${name} State"
    icon: "mdi:battery-charging"
    device_id: "${esphome_device_id}"
