defaults:
  name: "AB2000"
  # device_name: ""
  # device_id: ""
  # serial_number: ""

esphome:
  min_version: "2025.4.1"
  on_boot:
    - then:
        - lambda: |-
            id(${device_id}_batteries).insert(
              std::make_pair("${serial_number}", [](JsonObject pack) -> void {
                // Define a map of handlers for each key
                static const sensor_handler_map_t handlers = {
                  {"sn", [](int value) { /* ignore */ }},
                  {"power", [](int value) { id(${device_id}_battery_${serial_number}_power)->publish_state(value); }},
                  {"minVol", [](int value) { id(${device_id}_battery_${serial_number}_minVol)->publish_state(value / VOLTAGE_SCALE); }},
                  {"maxVol", [](int value) { id(${device_id}_battery_${serial_number}_maxVol)->publish_state(value / VOLTAGE_SCALE); }},
                  {"totalVol", [](int value) { id(${device_id}_battery_${serial_number}_totalVol)->publish_state(value / VOLTAGE_SCALE); }},
                  {"soh", [](int value) { id(${device_id}_battery_${serial_number}_soh)->publish_state(value / PERCENT_SCALE); }},
                  {"socLevel", [](int value) { id(${device_id}_battery_${serial_number}_socLevel)->publish_state(value); }},
                  {"softVersion", [](int value) { id(${device_id}_battery_${serial_number}_softVersion)->publish_state(decode_version(value)); }},
                  {"maxTemp", [](int value) { id(${device_id}_battery_${serial_number}_maxTemp)->publish_state((value / TEMPERATURE_SCALE) - TEMPERATURE_OFFSET); }},
                  {"state", [](int value) {
                    const char* state = (value == 0) ? "Idle" : (value == 1) ? "Charging" : "Discharging";
                    id(${device_id}_battery_${serial_number}_state)->publish_state(state);
                  }}
                };

                handle_sensor_object(pack, handlers, "${device_id}");
              })
            );

json:
zendure:

sensor:
  - platform: template
    id: "${device_id}_battery_${serial_number}_power"
    name: "${device_name} ${name} Power"
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
    accuracy_decimals: 0
  - platform: template
    id: "${device_id}_battery_${serial_number}_minVol"
    name: "${device_name} ${name} Min Vol"
    device_class: voltage
    state_class: measurement
    unit_of_measurement: "V"
    accuracy_decimals: 2
  - platform: template
    id: "${device_id}_battery_${serial_number}_maxVol"
    name: "${device_name} ${name} Max Vol"
    device_class: voltage
    state_class: measurement
    unit_of_measurement: "V"
    accuracy_decimals: 2
  - platform: template
    id: "${device_id}_battery_${serial_number}_totalVol"
    name: "${device_name} ${name} Total Vol"
    device_class: voltage
    state_class: measurement
    unit_of_measurement: "V"
    accuracy_decimals: 2
  - platform: template
    id: "${device_id}_battery_${serial_number}_soh"
    name: "${device_name} ${name} SoH"
    state_class: measurement
    icon: "mdi:battery-heart-variant"
    unit_of_measurement: "%"
    accuracy_decimals: 1
    entity_category: diagnostic
    disabled_by_default: true
  - platform: template
    id: "${device_id}_battery_${serial_number}_socLevel"
    name: "${device_name} ${name} SoC Level"
    device_class: battery
    state_class: measurement
    unit_of_measurement: "%"
    accuracy_decimals: 0
  - platform: template
    id: "${device_id}_battery_${serial_number}_maxTemp"
    name: "${device_name} ${name} Max Temp"
    device_class: temperature
    state_class: measurement
    unit_of_measurement: "°C"
    accuracy_decimals: 2
    entity_category: diagnostic
    disabled_by_default: true

text_sensor:
  - platform: template
    id: "${device_id}_battery_${serial_number}_softVersion"
    name: "${device_name} ${name} Soft Version"
    entity_category: diagnostic
    disabled_by_default: true
  - platform: template
    id: "${device_id}_battery_${serial_number}_state"
    name: "${device_name} ${name} State"
    icon: "mdi:battery-charging"
